services:
  testing:
    container_name: blogtest
    build:
      dockerfile: ./Docker/Dockerfile
      context: .
    volumes:
      - ./:/app
    ports:
    - 8080:8080
    environment:
      APP_ENV: development
    depends_on:
      - postgres
    networks:
      - database-net

  postgres:
    image: postgres
    networks:
      - database-net
    user: root
    environment:
      POSTGRES_USER: db_username
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - ./Docker/pg_sql:/docker-entrypoint-initdb.d/

networks:
  database-net: